### ISSUE TITLE
Unlock balance function remains "Locked"

### ISSUE THREAD

**Issue by Slim-strit** [celo-tools/celo-web-wallet#129]
#### App Version and Operating System

- Tested on  Othello update on 2/19/24 from previously installed CELO wallet
- Platform and version: Windows 11 with most recent updates

#### Expected behavior

Unlock CELO balance

#### Actual behavior

Transaction processed on celo blockchain success, but not unlocked inside wallet.

#### Steps to reproduce the behavior

Unable b/c no more tokens to attempt another unlock

**Comment by jmrossy** [comment]
Unlocked funds require 3 days before they can be withdrawn
