### ISSUE TITLE
Ledger: Logging out then back in requires app restart

### ISSUE THREAD

**Issue by jmrossy** [celo-tools/celo-web-wallet#29]
#### App Version and Operating System

- Tested on v1.0.0
- Platform and version: Mac

#### Expected behavior

Ledger users can log out and back in many times 

#### Actual behavior

After logging out, the app must be restarted before importing another Ledger account

**Comment by i1skn** [comment]
Also, when logging out the following message is unnecessary ( I would even say it can confuse)

<img width="629" alt="Screenshot 2021-03-30 at 22 19 57" src="https://user-images.githubusercontent.com/6160124/113081283-f9033f80-920a-11eb-9105-811f6849bce1.png">

**Comment by jmrossy** [comment]
@i1skn This bug and the confusing text you pointed out will be fixed in the next release, sorry it took so long :)
