### ISSUE TITLE
issue with locking Celo

### ISSUE THREAD

**Issue by sdstefanov** [celo-tools/celo-web-wallet#31]
Dear all, I recently downloaded and installed the Celo Wallet desktop app for Mac...Transferred some Celo from CoinList to my wallet..
When I tried to lock the Celo I got an error (not sure what it was but maybe I wanted to lock all Celo gold and I didn't have enough left for fees? (the popup disappears too quickly)).
I tried locking my Celo again using an amount less than the max and it gives me an error that I'm "Attempting to register account that already exists".
So right now I can't lock the Celo and validate it. Could you please assist? Maybe this is a bug that others may experience too.
Thank you in advance

**Comment by jmrossy** [comment]
@sdstefanov Sorry for not responding here sooner. 

Back in March we released an update which prevents users from trying to lock their whole balance. This will prevent future errors like this 🙂
