### ISSUE TITLE
Support other ERC20 tokens via Token Lists

### ISSUE THREAD

**Issue by macalinao** [celo-tools/celo-web-wallet#32]
#### Feature Description

It would be great to have native support for token lists in order to accommodate for the new tokens soon being launched on Celo.

Here's an example of a token list: https://github.com/Ubeswap/ubeswap-interface/blob/main/src/state/lists/ubeswap-default.tokenlist.json -- we'd probably have a separate repo specifically for a token list that we can easily collaborate on.

Is this something that might be possible soon? Or something I might be able to add in myself via a PR? Thanks!

**Comment by jmrossy** [comment]
@macalinao Sorry for not replying here sooner.

Yes we definitely want a shared ERC20 list for all wallets to consume. A few of us have discussed creating a new repo CeloOrg for this purpose.

In the meantime, CeloWallet's current list is here: https://github.com/celo-tools/celo-web-wallet/blob/master/src/erc20.ts
Please feel free to open PRs with additions :)
