### ISSUE TITLE
isSecretTooSimple fails for passwords longer than 32 characters

### ISSUE THREAD

**Issue by aaronmgdr** [celo-tools/celo-web-wallet#35]
isSecretTooSimple fails for passwords longer than 32 characters

this results in a misleading message in ui of "password is too simple" when in fact it is too long

https://github.com/celo-tools/celo-web-wallet/blob/e61ce1589bdcbe6d1c7773f2f96e4735600b9323/src/features/pincode/utils.ts#L20

**Comment by jmrossy** [comment]
Good catch, thanks @aaronmgdr! Should be an easy fix

**Comment by jmrossy** [comment]
I have some improvements to the password handling coming with the next update. It adds support up to 100 chars, adds helpful error messages for the various requirements, and adds a password strength bar :)

**Comment by jmrossy** [comment]
The improvements are now live in 1.2.0 😄
