### ISSUE TITLE
Connection to rpc providers fails

### ISSUE THREAD

**Issue by ianmunge0** [celo-tools/celo-web-wallet#56]
#### App Version and Operating System

- Tested on  **v1.2.2**
- Platform and version: **kali linux 2021.1**

#### Expected behavior

A smooth running on the first activity of Creating a new wallet/importing existing wallet

#### Actual behavior

Connecting to the network times out on this first activity. The logs show that it fails to connect to rpc providers after 3 attempts

#### Steps to reproduce the behavior

run `yarn electron:dev`
![celodesktoperror](https://user-images.githubusercontent.com/33924826/124252329-82d6e780-db2f-11eb-9def-a64e6dc4d804.png)

**Comment by jmrossy** [comment]
Hey @ianmunge0 

Thanks for opening an issue. Like we chatted about on Discord, can you try connecting from a different machine or a different location to see if the issue persists? And please also try syncing your machine's local clock as clock drift can cause problems with Celo network traffic.
