### ISSUE TITLE
Withdraw issue after staking

### ISSUE THREAD

**Issue by wacher74** [celo-tools/celo-web-wallet#66]
#### App Version and Operating System

Version: Celo Wallet 1.3.4
Windows 10 Pro x64

#### Expected behavior

Withdraw is successful.

#### Actual behavior

Withdraw is unsuccessful.

#### Steps to reproduce the behavior

I see in BALANCE:
	Locked CELO 30,21   (hmmm this is unlocked more than 3 days ago)

I see in LOCK:
	Ready to withdraw 30.21
	Locked 0

I click on Withdraw, max amount. Amount filled with 30.21
Amount   30.21   Max Amount
Result 
Unlocked  30.21

CONTINUE > 
Review Withdraw Request
Action	Withdraw
Value	CELO	30.21
Fee 	CELO	0.001
Unlocked	30.21
Pending		0
Locked		0

Withdraw Failed
Your Withdraw request could not be processed
Error: insufficient funds for intrinsic transaction cost (error={"reason":"proce...

Note #1: The error message is truncated in message box.
Note #2: "For other help, try asking in the Discord chat." -> this is just an empty window, no access for any discord channel.

**Comment by jmrossy** [comment]
@wacher74 Do you have any unlocked CELO funds to pay for this transaction?

As for the Discord link, you have to accept the server's rules before you can see the channels.

**Comment by wacher74** [comment]
It is locked
<img width="928" alt="Capture1" src="https://user-images.githubusercontent.com/24725150/132031873-6e64d29a-61bb-4373-b636-5cd4e239539f.PNG">
It is unlocked, ready to withdraw
<img width="928" alt="Capture2" src="https://user-images.githubusercontent.com/24725150/132031875-fb0bd0b1-cdd5-481b-bbb9-09fad0349f35.PNG">
It is unlocked
<img width="928" alt="Capture3" src="https://user-images.githubusercontent.com/24725150/132031877-c7980662-406f-4faa-be50-72f948b6742f.PNG">
There is nothing to accept:
<img width="1240" alt="Capture4" src="https://user-images.githubusercontent.com/24725150/132031879-1d42bdfa-0b86-4b6e-9a83-2a18ea5a9e13.PNG">

**Comment by wacher74** [comment]
public address 0xF170dd789B6D42d4C9AC69E19FB9c207644a644e

**Comment by wacher74** [comment]
Hello,
Could you help me to get my money back?

**Comment by jmrossy** [comment]
@wacher74 What happens when you Click the green Withdraw button and execute the transaction?

As for the Discord channel. I think there was a permissions issue with some channels. It should be fixed now :)

**Comment by wacher74** [comment]
Yes, channel is ok now :)
I'll try send to some coin back to wallet.

**Comment by wacher74** [comment]
Thank you very much for your help. My problem has been solved.
